### PR TITLE
[WIP] Remove Xemacs support

### PR DESCRIPTION
**Pull request by vxid**
See #50

### CODE REVIEW

**Comment by conao3** [comment]
LGTM.

**Comment by vxid** [comment]
@conao3 You should not merge this yet, I created the PR but did not add anything yet to it. I plan on working on this next week.

**Comment by conao3** [comment]
I thought that after deleting that declaration, you would do the necessary work before adding the next version tag.
I'm sorry.

**Comment by vxid** [comment]
No problem, I will open the PR when I am done working on this!

**Pull request merged**
