### PR TITLE
Re: remove all references to Bruce's email address

### PR DESCRIPTION
**Pull request by conao3**
Another reorganized PR instead of #28.

### CODE REVIEW

**Comment by tarsius** [comment]
> fix GitHub url

I would say it is an "update" not a "fix".

**Comment by conao3** [comment]
Absolutely.

**Comment by conao3** [comment]
Is this PR mergeable?

**Comment by tarsius** [comment]
Actually one more thing: since all the other commit messages begin with a capital letter, you should do the same.

**Comment by conao3** [comment]
Capitarized.

**Pull request merged**
